name: Build and lint

on:
  - push
  - pull_request

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format-18 clang-tidy-18 build-essential python3-pip
          pip3 install compiledb
          
      - name: Check format
        run: |
          find . -path ./build -prune -o -type f -name '*.[c|h]' -print | xargs clang-format-18 --style=file --dry-run -Werror
          
      - name: Generate compile_commands.json
        run: |
          echo 'gcc -c main.c -o main.o' > build_commands.txt
          compiledb -n build_commands.txt
          
      - name: Lint with clang-tidy
        run: |
          run-clang-tidy-18 -p=.
